modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Paperclippy/issues"
license="MIT"

[[mods]]
modId="paperclippy"
version="${file.jarVersion}"
displayName="Paperclippy"
displayURL="https://www.curseforge.com/minecraft/mc-mods/paperclippy"
authors="Mrbysco"
description='''
Paperclippy is helpful paperclip that follows you around and gives tips.
'''
[[dependencies.paperclippy]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.paperclippy]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.117-beta,)"
ordering="NONE"
side="BOTH"