modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/Paperclippy/issues"
license="MIT"

[[mods]]
modId="paperclippy"
version="${file.jarVersion}"
displayName="Paperclippy"
displayURL="https://www.curseforge.com/minecraft/mc-mods/paperclippy"
authors="Mrbysco"
description='''
Paperclippy is helpful paperclip that follows you around and gives tips.
'''
[[dependencies.paperclippy]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.paperclippy]]
modId="neoforge"
mandatory=true
versionRange="[20.2.86,)"
ordering="NONE"
side="BOTH"