modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Mrbysco/Paperclippy/issues"
license="MIT"

[[mods]]
modId="paperclippy"
version="${file.jarVersion}"
displayName="Paperclippy"
displayURL="https://www.curseforge.com/minecraft/mc-mods/paperclippy"
authors="Mrbysco"
description='''
Paperclippy is helpful paperclip that follows you around and gives tips.
'''
[[dependencies.paperclippy]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
[[dependencies.paperclippy]]
modId="forge"
mandatory=true
versionRange="[40.1.0,)"
ordering="NONE"
side="BOTH"